### ISSUE TITLE
Improve volcalc R package based on review

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/organization#888]
@dlebauer review

**Comment by KristinaRiemer** [comment]
https://github.com/Meredith-Lab/volcalc

**Comment by dlebauer** [comment]
Here are some other questions and suggestions. These can be moved to a separate issue 

- Overall, a nice and straightforward package. Great to see all of the functions documented, and fantastic to see tests.
- Is there a reason that `calc_vol` takes the pathway as an argument? Isn't volatility a physical property of a compound or does it depend on the pathway? For the first compound, volatility is the same for both pathways - is that expected?
- function documentation should contain a description of returned data frame
- are the variables log_alpha and log_Sum useful? If so, these should be documented (currently these are defined as 'intermediate step'. What are the units? Exclude if not useful.
- Is log_c the actual volatility, or is it the logarithm of volatility? Usually, the untransformed value is more useful. If this is the case, should return, define, and perhaps choose a more informative name than "c"
-Functions work but tests don't - when I run `check()` I get an error because they require the ChemmineOB package, which isn't available on Windows. is ChemmineOB (and thus MacOS or Linux) a requirement?

**Comment by Aariq** [comment]
Discussion on development of `volcalc` now happening here: https://github.com/Meredith-Lab/volcalc
